import type { MetadataRoute } from "next";

/**
 * Web app manifest — gives Android (and other browsers) the Recap icon and
 * name when someone adds the site to their home screen. Icons are
 * generated by scripts/generate-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Recap — Counselling & Psychological Services",
    short_name: "Recap",
    start_url: "/",
    display: "browser",
    background_color: "#fbf4ec",
    theme_color: "#fbf4ec",
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
